name: next_project_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: 'none'

environment:
  sdk: ^3.5.0-152

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  dcli: ^4.0.1-beta.4
  interact:
    path: packages/interact
  json: ^0.20.1
  path: ^1.9.0
  uuid: ^4.4.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
